# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jt < Formula
  desc "A lightweight CLI to pull Jira Cloud tickets into local markdown files"
  homepage "https://github.com/erickhilda/jt"
  version "0.1.3"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erickhilda/jt/releases/download/v0.1.3/jt_0.1.3_darwin_amd64.tar.gz"
      sha256 "b4a8a224a1883714ec0a448c1900212b8acc82110bdd3084322584adbda005b0"

      define_method(:install) do
        bin.install "jt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/erickhilda/jt/releases/download/v0.1.3/jt_0.1.3_darwin_arm64.tar.gz"
      sha256 "285cc5ab4e8c7b71a0e38bf6698bf28ed81c542a0c58a8b1eded1349586f8433"

      define_method(:install) do
        bin.install "jt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/erickhilda/jt/releases/download/v0.1.3/jt_0.1.3_linux_amd64.tar.gz"
      sha256 "6e878d81c442201a54f2a4799609851b492c4188760a6134bed981821d4e931b"
      define_method(:install) do
        bin.install "jt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erickhilda/jt/releases/download/v0.1.3/jt_0.1.3_linux_arm64.tar.gz"
      sha256 "3d3bf97ccae662f04c1dd5ccdd7ac8b8845e1198062ba2a7026a2ab50309317a"
      define_method(:install) do
        bin.install "jt"
      end
    end
  end
end
