# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Jt < Formula
  desc "A lightweight CLI to pull Jira Cloud tickets into local markdown files"
  homepage "https://github.com/erickhilda/jt"
  version "0.1.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/erickhilda/jt/releases/download/v0.1.2/jt_0.1.2_darwin_amd64.tar.gz"
      sha256 "5623f9a791604224f42b585276c55f9f4dd3d15ef7bdc14d67777c9ac25d4209"

      def install
        bin.install "jt"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/erickhilda/jt/releases/download/v0.1.2/jt_0.1.2_darwin_arm64.tar.gz"
      sha256 "c90bc758697fc5ee1ccd467d9b8ea949892ce91d76a20298144c544910d32967"

      def install
        bin.install "jt"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/erickhilda/jt/releases/download/v0.1.2/jt_0.1.2_linux_amd64.tar.gz"
      sha256 "39b866bc0aa1b17e3012e629513d0fdd23df7fb08e310da7c6f26605b3c3a012"
      def install
        bin.install "jt"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/erickhilda/jt/releases/download/v0.1.2/jt_0.1.2_linux_arm64.tar.gz"
      sha256 "8d7e2d7dc142b2cadbb6f18a19641ee84642d441a14e1bfdea5fb5348df8a589"
      def install
        bin.install "jt"
      end
    end
  end
end
